name = "GamersBuried"
author = "Gamers"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97fd057071c5efe15521edfe1c9294783015a697786b5ec0e2acc2695c5fb525"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
