name = "GamersBuried"
author = "Den4enko"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70f8565ed033f2704525f3771ebb955364e9f03456b16be47519f293d956910a"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
