name = "GamersBuried"
author = "Gamers"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f64e8f6eb1a49951785e63dcc3060bcfc67f6fe55ed8c74e685dd4445ffdf35"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
