name = "GamersBuried"
author = "Den4enko"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d905502cf5accc0bb87b249656f61424dad348335155f9bd7872238eea74e7c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
