name = "GamersBuried"
author = "Den4enko"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e45657c56c728944305daf21c3e0eb0f0a029391c2a27758baef14cdd500772"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
